### PR TITLE
template, new reqs

### PR DESCRIPTION
**Pull request by pmlandwehr**
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by pmlandwehr** [comment]
@conda-forge-admin please rerender

**Comment by cpcloud** [comment]
@pmlandwehr Can you please take a look at [this PR](https://github.com/conda-forge/multipledispatch-feedstock/pull/7) for the multiple dispatch feedstock? If you're not maintaining that feedstock anymore, I'm happy to take it over.

**Comment by carlodri** [comment]
What is this PR for?

**Comment by pmlandwehr** [comment]
@carlodri Nothing, at this point, since the other pull's merged. Closing this up!

**Pull request closed without merging**
